Update source of total aptc for calculation
ideacrew/enroll pull request #1290
Opened 2021-11-04 20:08 UTC by RyanEddyIC

2021-11-04 20:35 UTC, markgoho reviewed
@RyanEddyIC if this is a bug fix, where is the failing test that has now been fixed with this change in code?

2021-11-04 20:37 UTC, RyanEddyIC commented
@markgoho there was no failing test.

2021-11-04 20:45 UTC, markgoho commented
Yes, so let's write one 🤓

2021-11-09 17:46 UTC, ymhari requested changes

2021-11-09 17:46 UTC, ymhari commented on app/models/insured/factories/self_service_factory.rb
> +        reinstatement.update_attributes!(elected_aptc_pct: (cd_total_aptc / max_applicable_aptc), applied_aptc_amount: cd_total_aptc, aggregate_aptc_amount: max_applicable_aptc)
Add test cases where 
1. The aptc amount for the family is greater than the product premium. 
2. The aptc amount is less than the product premium.
3. And pct value should ignore ehb of product, so when the an elected aptc is greater than enrollment premium, applied aptc amount will be less than 100% however we still need the pct as 1.

2021-11-19 16:42 UTC, ymhari approved these changes
Fixes pct ratio calculation during apply aggregate.

2021-11-19 16:42 UTC, merged