ref: 180268920 Adds RR settings for report generation.
ideacrew/enroll pull request #1316
Opened 2021-11-10 23:24 UTC by ymhari

2021-11-10 23:55 UTC, markgoho requested changes

2021-11-10 23:55 UTC, markgoho commented on config/client_config/dc/system/config/templates/features/enroll_app/enroll_app.yml
> +      - key: :carrier_abbev_list
is `abbev` supposed to be `abbrev`?

2021-11-10 23:55 UTC, markgoho commented on spec/lib/tasks/pay_now_click_tracking_spec.rb
> +    context 'carrier for dc' do
there should be no mention of clients in spec files -- please refactor to generalize these specs

2021-11-10 23:55 UTC, markgoho commented on spec/lib/tasks/pay_now_click_tracking_spec.rb
> +    context 'carrier for me' do
same as above, specs should be client-agnostic

2021-11-10 23:55 UTC, markgoho commented
@ymhari please add a ticket reference to the comment box at the top

2021-11-12 03:06 UTC, markgoho approved these changes
changes look good, thanks @ymhari 👍🏻

2021-11-15 20:13 UTC, RyanEddyIC approved these changes

2021-11-15 21:38 UTC, merged