Ensure an application is only transferred once
ideacrew/enroll pull request #1375
Opened 2021-11-29 21:52 UTC by kristinmerbach

ME-180468508

2021-11-29 22:33 UTC, mdkaraman approved these changes, later dismissed

2021-11-29 23:32 UTC, markgoho requested changes
@kristinmerbach where is the test that fails if an application is transferred more than once?

2021-12-02 20:08 UTC, kristinmerbach commented
Spec has been added @markgoho !

2021-12-02 20:11 UTC, mdkaraman approved these changes

2021-12-02 20:28 UTC, markgoho approved these changes

2021-12-02 20:45 UTC, merged