ref: 180484144 configures connectivity test for carriers.
ideacrew/enroll pull request #1393
Opened 2021-12-02 21:50 UTC by ymhari

2021-12-02 21:57 UTC, markgoho requested changes
Please remove ticket from title and format ticket reference properly

2021-12-02 21:58 UTC, markgoho reviewed
Also, why are we adding so many low level flags instead of one high level flag?

2021-12-02 22:00 UTC, RyanEddyIC approved these changes

2021-12-03 12:50 UTC, markgoho approved these changes

2021-12-03 13:09 UTC, merged