Fixes no sponsored benefit issue
ideacrew/enroll pull request #1398
Opened 2021-12-03 21:50 UTC by utkarsh7989

RM-97080

2021-12-06 15:04 UTC, vineelsonnathi approved these changes, later dismissed
LGTM

2021-12-06 17:36 UTC, markgoho submitted a review, later dismissed
@utkarsh7989 if the ticket represents a bug or you are clearly fixing something that's broken - it needs to have a spec change associated with it

2021-12-07 18:47 UTC, vineelsonnathi approved these changes, later dismissed
LGTM. 
Specs written.

2021-12-07 22:15 UTC, markgoho requested changes

2021-12-07 22:15 UTC, markgoho commented on components/benefit_sponsors/spec/views/benefit_sponsors/benefit_applications/edit.html.slim_spec.rb
> +    expect(rendered).to_not match(/Reference Plans/)
please do not use hard-coded english text to assert on, please use an element, or a css class/attribute

2021-12-08 15:13 UTC, vineelsonnathi approved these changes
LGTM.

2021-12-08 15:45 UTC, markgoho approved these changes

2021-12-08 15:45 UTC, merged