Add extra condition on missing Maine county
ideacrew/enroll pull request #1445
Opened 2021-12-10 21:57 UTC by jacobkagon

ME-180547733

2021-12-10 22:00 UTC, bill-transue approved these changes, later dismissed
Fixes the address_needs_fixing for counties that have bad data in it.

2021-12-10 22:01 UTC, bill-transue commented
This doesn't need to be spec'ed because it was developed in the PVT-3 console directly so that it could used with real data.

2021-12-10 22:30 UTC, markgoho requested changes
@jacobkagon please add or adjust specs here `spec\lib\tasks\fix_maine_nil_counties_spec.rb` to reflect the changes made to these methods

2021-12-11 01:52 UTC, markgoho approved these changes

2021-12-11 01:52 UTC, merged