Fix for income fix
ideacrew/enroll pull request #1514
Opened 2021-12-24 01:10 UTC by bill-transue

2021-12-24 01:28 UTC, jacobkagon submitted a review, later dismissed
This checks if income.amount is present as well as the amount is greater than zero. Thanks @bill-transue!

2021-12-24 02:15 UTC, markgoho requested changes
@bill-transue where is the ticket reference and specs?

2021-12-27 14:50 UTC, markgoho approved these changes, later dismissed

2021-12-27 17:12 UTC, vkghub approved these changes
This fix will resolve undefined method `>' for nil:NilClass

2021-12-27 17:12 UTC, merged