Populate tabacco attestation for enr members on apply …
ideacrew/enroll pull request #1516
Opened 2021-12-27 22:01 UTC by ymhari

[ME-180750688](https://www.pivotaltracker.com/story/show/180750688)

2021-12-27 22:03 UTC, markgoho requested changes, later dismissed
please shorten title to ~50 characters or less

please add QA plan to ticket

2021-12-28 02:15 UTC, nisanthyaganti9 requested changes

2021-12-28 02:15 UTC, nisanthyaganti9 commented on app/models/enrollments/replicator/reinstatement.rb
> +          tobacco_use = (tobacco_use == 'unknown') ? nil : tobacco_use
can we do below to keep it consistent.

```
tobacco_use = is_tobacco_user == 'unknown' ? 'NA' : is_tobacco_user
```

2021-12-28 14:25 UTC, nisanthyaganti9 submitted a review, later dismissed

2021-12-28 14:33 UTC, nisanthyaganti9 approved these changes

2021-12-28 14:53 UTC, merged