pivotal_180721616:  Update EDI logic to exclude Broker Assistors & Imported broker assignment
ideacrew/enroll pull request #1528
Opened 2021-12-30 08:01 UTC by saimekala07

https://www.pivotaltracker.com/n/projects/2502930/stories/180721616

2021-12-30 13:52 UTC, markgoho requested changes, later dismissed
please update title to remove ticket reference and be less than ~50 characters

please fix ticket reference in PR to look like `ME-<num>`

2022-08-24 20:05 UTC, saipraveen18 submitted a review, later dismissed
LGTM 👍

2022-08-25 13:30 UTC, saipraveen18 submitted a review, later dismissed

2022-08-25 15:21 UTC, markgoho submitted a review, later dismissed

2022-08-25 17:17 UTC, saipraveen18 approved these changes

2022-08-25 17:41 UTC, merged