Remove medicaid during pregnancy validations for ME
ideacrew/enroll pull request #1552
Opened 2022-01-07 21:06 UTC by RyanEddyIC

ME_180756519

2022-01-09 21:39 UTC, markgoho requested changes, later dismissed

2022-01-09 21:39 UTC, markgoho commented on components/financial_assistance/app/views/financial_assistance/applicants/other_questions.html.erb
> +            <span class="fa-text-color">Was this person enrolled in Medicaid during the pregnancy? <%= '*' if FinancialAssistanceRegistry.feature_enabled?(:is_enrolled_on_medicaid) %></span>
Text needs to be in a translation

2022-01-09 21:39 UTC, markgoho commented on components/financial_assistance/app/models/financial_assistance/applicant.rb
> +        errors.add(:is_enrolled_on_medicaid, "' Was this person on Medicaid during pregnancy?' should be answered") if is_enrolled_on_medicaid.nil? && is_applying_coverage && FinancialAssistanceRegis
If this shows to the end user, it should be in a translation string

2022-01-11 17:44 UTC, jayreddy519 approved these changes
LGTM.

Added Comments to the ticket.

2022-01-11 18:30 UTC, merged