180956164 populate evidence verification histories
ideacrew/enroll pull request #1579
Opened 2022-01-19 19:52 UTC by raghuramg

#180956164

2022-01-19 19:57 UTC, markgoho requested changes, later dismissed
please remove ticket reference from PR title

please format ticket reference like ME-<num> or IVL-<num> without the markdown link

2022-01-20 20:54 UTC, ipublic approved these changes, later dismissed

2022-01-20 20:54 UTC, ipublic commented on app/models/eligibilities/evidence.rb
> +    include Mongoid::Attributes::Dynamic
need to remove this from model

2022-01-20 21:10 UTC, ipublic approved these changes

2022-01-20 21:22 UTC, merged