181206072: Fixing Carrier Initiated Cancel
ideacrew/enroll pull request #1653
Opened 2022-02-10 04:35 UTC by saimekala07

ME-181206072

2022-02-10 13:17 UTC, markgoho commented on spec/models/subscribers/policy_terminations_subscriber_spec.rb
> +    FactoryBot.create(:hbx_enrollment, effective_on: Date.new(2022,2,1),
are these dates arbitrary?

2022-02-10 15:35 UTC, saimekala07 commented on spec/models/subscribers/policy_terminations_subscriber_spec.rb
> +  let(:termination_date) { Date.new(2022, 1, 1) }
Testing for the scenario with speciics dates and the expected outcome

2022-02-14 19:42 UTC, TreyE requested changes
Please see my comments.

2022-02-14 21:15 UTC, saimekala07 commented on app/models/subscribers/policy_terminations_subscriber.rb
> +              else
@TreyE Adding transition from `terminated` to `canceled` for coverage cancel event which creates an unnecessary issue that does not happen frequently and which does not happen through UI and as these are retro cancel and exceptions I'm handing manually by updating state and recording state transitions.

2022-02-14 22:08 UTC, TreyE approved these changes

2022-02-15 13:44 UTC, kristinmerbach approved these changes

2022-02-15 13:44 UTC, merged