181147353 plan confirmation display
ideacrew/enroll pull request #1663
Opened 2022-02-17 14:08 UTC by jayreddy519

[PT-181147353](https://www.pivotaltracker.com/n/projects/2502930/stories/181147353)

2022-02-23 20:44 UTC, ymhari requested changes

2022-02-23 20:44 UTC, ymhari commented on app/domain/operations/individual/fetch_existing_coverage.rb
> +        all_enrollments = HbxEnrollment.where({:family_id.in => family_ids, :aasm_state => {"$in" => HbxEnrollment::ENROLLED_STATUSES + HbxEnrollment::RENEWAL_STATUSES }, coverage_kind:  enrollment.f
Should the auto-renewal be considered as existing coverage?

2022-02-23 20:44 UTC, ymhari commented on app/controllers/insured/plan_shoppings_controller.rb
> +    return [] if existing_dependent_enrollments.nil? || existing_dependent_enrollments.count == 0
No value is returning an empty array here.

2022-02-23 20:44 UTC, ymhari commented on app/views/insured/plan_shoppings/_prior_coverage_information.html.erb
> +        	<h4><%= l10n("coverage_info_msg") %> <%= l10n("site_url") %></h4>
This is not a url.

2022-02-23 20:44 UTC, ymhari commented on config/client_config/dc/system/config/templates/features/enroll_app/enroll_app.yml
> +      - key: :fetch_existing_coverage
Change the key name.

2022-02-23 20:44 UTC, ymhari commented on app/views/insured/plan_shoppings/thankyou.html.erb
> +          <%= render partial: "insured/plan_shoppings/prior_coverage_information", locals: {dependent_members: @dependent_members} if @dependent_members.present? && EnrollRegistry.feature_enabled?(:f
Do we need an RR setting check here?

2022-02-23 20:44 UTC, ymhari commented on app/domain/operations/individual/fetch_existing_coverage.rb
> +  module Individual
This is a generic operation not specific to individual market.

2022-02-23 20:44 UTC, ymhari commented on spec/domain/operations/individual/fetch_existing_coverage_spec.rb
> +    let!(:enrollment1) do
Do we need 6 enrollment here? Can we mock some if needed?

2022-02-23 20:44 UTC, ymhari commented on spec/domain/operations/individual/fetch_existing_coverage_spec.rb
> +    context "hbx enrollment members with shopping enrollment" do
Incorrect context the operation doesn't care that it should not work for the shop market.  Rather this context should be in the controller spec.

2022-02-23 20:44 UTC, ymhari commented on spec/domain/operations/individual/fetch_existing_coverage_spec.rb
> +
Need more scenarios to check the market_kind, coverage_kind, what is the enrollment as no dependents, and if the enrollments are missing family_ids.

2022-02-24 17:47 UTC, ymhari approved these changes
Adds a warning message when dependents are already enrolled in another active enrollment.

2022-02-24 17:52 UTC, RyanEddyIC approved these changes

2022-02-24 18:04 UTC, merged