capitalize broker legal name
ideacrew/enroll pull request #1684
Opened 2022-03-07 18:11 UTC by jacobkagon

ME-181346809

2022-03-07 20:51 UTC, raghuramg requested changes
Please make requested changes. Thank you

2022-03-07 20:51 UTC, raghuramg commented on app/views/insured/families/_consumer_brokers_widget.html.erb
> +          <%=  current_broker_agency&.broker_agency_profile&.legal_name&.split(" ")&.map(&:capitalize).join(" ") %>
can you do `titleize` instead

2022-03-09 19:29 UTC, raghuramg approved these changes
Code fix looks good. Please promote this for testing

2022-03-09 19:37 UTC, kristinmerbach approved these changes

2022-03-09 19:51 UTC, merged