Rescue to copy action
ideacrew/enroll pull request #1732
Opened 2022-04-04 22:13 UTC by nisanthyaganti9

ME-181630225

2022-04-05 18:07 UTC, saikumar9 requested changes

2022-04-05 18:07 UTC, saikumar9 commented on components/financial_assistance/app/controllers/financial_assistance/applications_controller.rb
> +      flash[:error] = "Failed with error - #{e}"
@nisanthyaganti9
1. Add translations for the text as it displays to the user.
2. Did you mean to use **e.message** instead of **e**?

2022-04-05 18:07 UTC, saikumar9 commented on components/financial_assistance/spec/controllers/financial_assistance/applications_controller_spec.rb
> +      it 'redirects when ApplicationService raises an error' do
Good test coverage.

2022-04-05 20:16 UTC, saikumar9 approved these changes

2022-04-08 13:07 UTC, nisanthyaganti9 commented
@markgoho - can you enable auto merge on this PR ?

2022-04-08 19:46 UTC, merged