182374103: Drop enrollment members - for IAP flow
ideacrew/enroll pull request #1856
Opened 2022-06-09 06:28 UTC by vkghub

[DC-182374103](https://www.pivotaltracker.com/n/projects/2481183/stories/182374103)

2022-06-10 17:26 UTC, ymhari requested changes

2022-06-10 17:26 UTC, ymhari commented on system/config/templates/features/aca_individual_market/aca_individual_market.yml
> +      - key: :yearly_aggregate_drop_enrollment_member
Change the name to something like, check_member_enrollment_eligibility.

2022-06-14 03:53 UTC, vkghub commented on app/models/insured/factories/self_service_factory.rb
> +      def self.remove_invalid_enrollment_members(reinstatement)
drop_selected_members methods is specific to the dropped member that is passed in params, this cannot be used in the current context.

2022-06-16 20:28 UTC, ymhari approved these changes

2022-06-16 20:46 UTC, merged