add missing translations
ideacrew/enroll pull request #2004
Opened 2022-08-12 14:41 UTC by jacobkagon

IVL-182973141

2022-08-12 16:26 UTC, markgoho requested changes
@jacobkagon we may need to tweak how we do this sanitization

2022-08-12 16:32 UTC, jacobkagon commented on components/financial_assistance/app/views/financial_assistance/applications/_combined_eligibility_results.html.erb
> +            <%= sanitize link_to l10n("faa.results.view_my_applications"), applications_path, class: "btn btn-small btn-primary" %>
@markgoho this was the suggestion from codesweep

2022-08-15 23:01 UTC, kristinmerbach approved these changes
Looks good to me.

2022-08-16 13:41 UTC, markgoho approved these changes

2022-08-16 13:42 UTC, merged