adding tax household group persistance models
ideacrew/enroll pull request #2032
Opened 2022-08-23 00:55 UTC by nisanthyaganti9

2022-09-10 19:25 UTC, saikumar9 requested changes
There are just a couple of changes. These are not blockers.

2022-09-10 19:25 UTC, saikumar9 commented on app/domain/operations/premium_credits/find_csr_value.rb
> +        @subjects = @subjects.reject { |subject| family_members_with_ai_an.include? subject.person_id.to_s }
These lines are not needed as you are already setting the CSR Hash above.

2022-09-10 19:25 UTC, saikumar9 commented on app/models/benefit_coverage_period.rb
> +  # @param group_member_premium_credit [ GroupMemberPremiumCredit ] if eligible for financial assistance
Update Comment appropriately.

2022-09-12 21:53 UTC, saikumar9 submitted a review, later dismissed
Changes look good!

2022-09-19 20:41 UTC, saikumar9 submitted a review, later dismissed
LGTM!

2022-09-20 15:46 UTC, harshaellanki approved these changes

2022-09-20 15:47 UTC, merged