Ticket 183325829
ideacrew/enroll pull request #2132
Opened 2022-09-22 20:03 UTC by saipraveen18

ME-183325829

2022-11-07 17:23 UTC, markgoho requested changes

2022-11-07 17:23 UTC, markgoho commented on Gemfile.lock
> +  revision: a16a305db371208c885a659d6cb736362b4572e1
why not the latest sha?

2022-11-07 17:24 UTC, markgoho requested changes, later dismissed

2022-11-07 17:24 UTC, markgoho commented on config/client_config/dc/system/config/templates/features/brokers/brokers.yml
> +        is_enabled: false
why are these hard-coded rather than based on environment variables?

2022-12-05 00:41 UTC, TreyE approved these changes, later dismissed
Needs the changes mark mentioned but otherwise seems correct, especially since we reduce the broker change into a single action.

2022-12-05 15:19 UTC, saipraveen18 commented
> Needs the changes mark mentioned but otherwise seems correct, especially since we reduce the broker change into a single action.

Addressed changes mentioned by Mark

2022-12-05 15:23 UTC, markgoho commented on system/config/templates/features/brokers/brokers.yml
> +        is_enabled: <%= ENV['BROKER_HIRED_EVENT_TO_EDI_IS_ENABLED'] || false %>
do we need to independently turn these on and off? why not just a `BROKER_EDI_EVENT_IS_ENABLED`?

2022-12-05 18:18 UTC, TreyE approved these changes
Re-approving.

2022-12-05 18:19 UTC, merged