add enrollment history page
ideacrew/enroll pull request #2263
Opened 2022-10-17 22:07 UTC by mdkaraman

IVL-183235259

2022-10-20 15:58 UTC, markgoho requested changes, later dismissed

2022-10-20 15:58 UTC, markgoho commented on features/step_definitions/individual_steps.rb
> +  expect(page).to have_no_link('Enrollments')
should be css driven rather than english text

2022-10-20 15:58 UTC, markgoho commented on features/step_definitions/individual_steps.rb
> +  link_text = l10n("enrollment_history_nav_label")
should be css driven rather than text

2022-10-20 15:58 UTC, markgoho commented on features/step_definitions/individual_steps.rb
> +  find_link(link_text).click
should be css driven rather than text

2022-10-20 15:58 UTC, markgoho commented on features/step_definitions/individual_steps.rb
> +  expect(page).to have_content(title)
should be css driven rather than text

2022-10-21 18:59 UTC, polographer approved these changes
looks good !

2022-10-21 19:21 UTC, merged