update text to applications page for consumers
ideacrew/enroll pull request #2388
Opened 2022-11-15 19:55 UTC by j1joey

ME-183726587

2022-11-15 20:33 UTC, markgoho commented
@j1joey I think you also need the translation key/string added to the dc translation file

2022-11-16 17:21 UTC, markgoho requested changes, later dismissed

2022-11-17 03:50 UTC, j1joey commented on spec/domain/operations/individual/apply_aggregate_to_enrollment_spec.rb
> +      expect(family.hbx_enrollments.to_a.first.applied_aptc_amount).to eq family.hbx_enrollments.last.applied_aptc_amount
This was actually a test that was causing trunk to fail, I thought it had to do with my ticket but I resolved it in another pr. Ill take it out of this one now that its not necessary and pull in the changes

2022-11-17 14:52 UTC, jacobkagon requested changes

2022-11-17 14:52 UTC, jacobkagon commented on components/financial_assistance/db/seedfiles/translations/en/ic/financial_assistance.rb
> +  "en.faa.update_reminder" => "If you make changes to your %{year} coverage that should apply to your %{year2} coverage too, you will need to come back and update your %{year2} application. You can d
Add a comma at the end of this line

2022-11-17 16:27 UTC, jacobkagon approved these changes, later dismissed
Adds new paragraph on the application year page instructing applicants to update their 2023 applications if they made changes to their 2022 application. LGTM!

2022-11-17 16:35 UTC, jacobkagon commented on components/financial_assistance/app/views/financial_assistance/applications/index.html.erb
> +          <h4><b><%= l10n('faa.coverage_update_reminder', year: oe_year, year2: current_year) %></b></h4>
@j1joey are the placement of the years correct? OE year will be the next year, while current year is this year.

2022-11-17 18:12 UTC, jacobkagon commented on components/financial_assistance/app/views/financial_assistance/applications/index.html.erb
> +          <h4><b><%= l10n('faa.coverage_update_reminder', year: oe_year, year2: current_year) %></b></h4>
Updated the dates

2022-11-17 18:13 UTC, jacobkagon approved these changes
Updated the dates to reflect current year and following year accurately

2022-11-17 18:14 UTC, merged