Update Tax Household Logic
ideacrew/enroll pull request #2419
Opened 2022-12-01 16:18 UTC by j1joey

ME-183810254

2022-12-01 17:21 UTC, markgoho submitted a review, later dismissed
missing a spec here that should have been failing prior to this fix

2022-12-08 14:30 UTC, nisanthyaganti9 requested changes

2022-12-08 14:30 UTC, nisanthyaganti9 commented on spec/domain/operations/premium_credits/find_aptc_spec.rb
>            )
Can you add a new context with another example by building eligibility determination with inactive tax household in it

2022-12-09 17:55 UTC, markgoho submitted a review, later dismissed
please rebase properly to remove other's commits from the history on this branch

2022-12-13 18:17 UTC, nisanthyaganti9 approved these changes

2022-12-13 20:47 UTC, merged