Bug 100785
ideacrew/enroll pull request #2489
Opened 2022-12-27 20:43 UTC by utkarsh7989

2022-12-30 16:54 UTC, RyanEddyIC approved these changes, later dismissed

2023-01-04 16:30 UTC, saikumar9 requested changes
@utkarsh7989 @RyanEddyIC We should really be relaxing the aca_entities contract and entity when the person is not applying for coverage instead of setting nil values for these fields

2023-01-09 01:47 UTC, saikumar9 approved these changes

2023-01-09 14:39 UTC, saikumar9 requested changes
We will be losing data if we are overriding what they entered instead we should not populate this information as part of the Cv3Applicaton payload when a person is not applying for coverage and also relax the aca_entities contract, entity validations when a person is not applying for coverage.

2023-06-23 20:57 UTC, closed without merging