Clear default GA feature changes
ideacrew/enroll pull request #2513
Opened 2023-01-05 16:03 UTC by utkarsh7989

RM-98116

2023-01-11 21:09 UTC, RyanEddyIC approved these changes, later dismissed

2023-02-09 14:18 UTC, polographer requested changes

2023-02-09 14:18 UTC, polographer commented on components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/_general_agencies.html.erb
> +      <%= sanitize link_to "#{l10n("clear_default_ga")}", '#', data: {toggle: "modal", target: "#clear_ga_confirm"}, class: 'btn btn-default btn-default pull-right' %>
the changes on this file don't have a corresponding test, can we add them?

2023-02-09 17:12 UTC, polographer commented on components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/_general_agencies.html.erb
> +      <%= sanitize link_to "#{l10n("clear_default_ga")}", '#', data: {toggle: "modal", target: "#clear_ga_confirm"}, class: 'btn btn-default btn-default pull-right' %>
leaving out for now because of business urgency

2023-02-09 17:12 UTC, polographer submitted a review, later dismissed

2023-02-09 20:45 UTC, RyanEddyIC approved these changes, later dismissed

2023-02-09 20:46 UTC, polographer submitted a review, later dismissed

2023-03-06 14:00 UTC, RyanEddyIC approved these changes

2023-03-06 15:31 UTC, polographer approved these changes

2023-03-06 15:31 UTC, merged