Update EDI when a broker agency is decertified
ideacrew/enroll pull request #2538
Opened 2023-01-18 14:49 UTC by saipraveen18

# PR Checklist

Please check if your PR fulfills the following requirements
- [X] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [X] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket: IVL-184251541

# A brief description of the changes

Current behavior: When a broker is decertified, broker decertification events for families under that broker were not flowing to EDI

New behavior: When a broker is decertified, broker decertification events for families under that broker will now flow to EDI

# Environment Variable

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. Please share the name of the variable below that would enable/disable the feature and which client it applies to.

Variable name:

- [ ] DC
- [ ] ME

2023-01-25 02:47 UTC, TreyE submitted a review, later dismissed

2023-01-25 14:18 UTC, nks2109 requested changes
can you add a test case when a broker is an assistor?

2023-01-25 14:46 UTC, saipraveen18 commented
> can you add a test case when a broker is an assistor?

Spec added

2023-01-25 15:09 UTC, nks2109 approved these changes
Updates EDI properly when a broker agency is decertified. Looks Good!

2023-01-26 16:47 UTC, TreyE approved these changes

2023-01-26 18:02 UTC, jayreddy519 approved these changes
This change Updates EDI when BA is decertified.
Added spec for the change.

LGTM.

2023-01-26 19:08 UTC, merged