auto update non_primary_applicants address when primary changes the a…
ideacrew/enroll pull request #2623
Opened 2023-03-10 13:38 UTC by vkghub

…ddress

# PR Checklist

Please check if your PR fulfills the following requirements
- [ ] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket: [Pivotal-184087847](https://www.pivotaltracker.com/n/projects/2502930/stories/184087847)

# A brief description of the changes

Current behavior:

New behavior:

# Environment Variable

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. Please share the name of the variable below that would enable/disable the feature and which client it applies to.

Variable name:

- [ ] DC
- [ ] ME

2023-03-14 13:30 UTC, saikumar9 requested changes

2023-03-14 13:30 UTC, saikumar9 commented on components/financial_assistance/app/models/financial_assistance/application.rb
> +    def update_dependents
Can you please rename the method name to be more meaningful?

2023-03-15 03:04 UTC, saikumar9 approved these changes

2023-03-15 13:10 UTC, jacobkagon approved these changes
nice!

2023-03-15 13:11 UTC, merged