setup MTHH data for reinstate enrollment
ideacrew/enroll pull request #2650
Opened 2023-03-18 17:28 UTC by vkghub

# PR Checklist

Please check if your PR fulfills the following requirements
- [ ] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket: [Pivotal-184695341](https://www.pivotaltracker.com/n/projects/2502930/stories/184695341)

# A brief description of the changes

Current behavior:

New behavior:

# Environment Variable

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. Please share the name of the variable below that would enable/disable the feature and which client it applies to.

Variable name:

- [ ] DC
- [ ] ME

2023-03-21 14:18 UTC, saipraveen18 submitted a review, later dismissed

2023-03-29 12:52 UTC, nisanthyaganti9 reviewed
@vkghub - Also run this by Sarah & @saikumar9.

Existing functionality is - we fetch `elected_aptc_pct` and `applied_aptc_amount` from base enrollment while creating reinstatement.

This PR will also update aptc values with current household composition along with creating tax household enrollments. Not sure, if we need to do this.

2023-03-29 15:07 UTC, saikumar9 requested changes

2023-03-29 15:07 UTC, saikumar9 commented on app/models/hbx_enrollment.rb
> +    create_or_update_mthh_data(new_effective_date, reinstate_enrollment, self.elected_aptc_pct)
Please clone TaxHouseholdEnrollments instead of recreating them.

2023-03-29 15:07 UTC, saikumar9 commented on spec/models/hbx_enrollment_spec_3.rb
> +  context "reinstate aptc enrollment" do
Good Test coverage!

2023-04-05 14:25 UTC, saikumar9 approved these changes
Changes look good to me

2023-04-05 14:34 UTC, saipraveen18 approved these changes

2023-04-05 14:42 UTC, merged