transform only determined applications to cv3
ideacrew/enroll pull request #2702
Opened 2023-04-02 19:01 UTC by vkghub

# PR Checklist

Please check if your PR fulfills the following requirements
- [ ] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket: [ME-184815644](https://www.pivotaltracker.com/n/projects/2502930/stories/184815644)

# A brief description of the changes

Current behavior:

New behavior:

# Environment Variable

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. Please share the name of the variable below that would enable/disable the feature and which client it applies to.

Variable name:

- [ ] DC
- [ ] ME

2023-04-02 20:04 UTC, saikumar9 requested changes

2023-04-02 20:04 UTC, saikumar9 commented on app/domain/operations/transformers/family_to/cv3_family.rb
> +          applications = ::FinancialAssistance::Application.where(family_id: family.id).where(:aasm_state.in => ["determined"])
```suggestion
          applications = ::FinancialAssistance::Application.where(family_id: family.id, aasm_state: 'determined')
```

2023-04-02 20:07 UTC, vkghub commented on app/domain/operations/transformers/family_to/cv3_family.rb
> +          applications = ::FinancialAssistance::Application.where(family_id: family.id).where(:aasm_state.in => ["determined"])
good catch

2023-04-02 20:07 UTC, vkghub commented on app/domain/operations/transformers/family_to/cv3_family.rb
> +          applications = ::FinancialAssistance::Application.where(family_id: family.id).where(:aasm_state.in => ["determined"])
let me update

2023-04-02 20:15 UTC, saikumar9 approved these changes

2023-04-11 18:10 UTC, saipraveen18 approved these changes

2023-04-11 18:10 UTC, merged