display tribal-name field if featured_tribes_selection is disabled
ideacrew/enroll pull request #2720
Opened 2023-04-11 12:45 UTC by vkghub

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket:  [ME-184025847](https://www.pivotaltracker.com/n/projects/2502930/stories/184025847)

# A brief description of the changes

Current behavior:  Tribal name required filed is not displayed to user when the value is nil or empty

New behavior: Always display the Tribal name required filed irrespective of the presence of its value only when featured_tribes_selection is disabled

# Environment Variable

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. Please share the name of the variable below that would enable/disable the feature and which client it applies to.

Variable name:

- [ ] DC
- [ ] ME

2023-04-12 14:53 UTC, jacobkagon approved these changes, later dismissed
Adds code to display tribal textbox without text for ME context. Looks good @vkghub

2023-04-12 18:07 UTC, jacobkagon approved these changes, later dismissed

2023-04-25 13:59 UTC, saikumar9 requested changes

2023-04-25 13:59 UTC, saikumar9 commented on app/assets/javascripts/demographics_fields.js
> +    if (enroll_state_abbr === 'ME') {
Make use of RR configuration instead of comparing these against the hardcoded text.

2023-04-25 13:59 UTC, saikumar9 commented on app/views/insured/consumer_roles/_tribe_fields.html.erb
> +    if (enroll_state_abbr === 'ME') {
Same here. Make use of RR configuration instead of comparing these against the hardcoded text.

2023-04-25 13:59 UTC, saikumar9 commented on features/insured/individual_with_featured_tribe_selection_disabled.feature
> +Feature: For the enabled AI/AN feature, existing consumer edits the personal info page
Good test coverage 👏

2023-04-25 16:01 UTC, jacobkagon approved these changes
nice!

2023-04-25 16:15 UTC, saikumar9 approved these changes
LGTM!

2023-04-25 16:15 UTC, merged