prevent default when hitting tab on enrollment page
ideacrew/enroll pull request #2745
Opened 2023-04-20 17:12 UTC by jacobkagon

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket: ME-184874008

# A brief description of the changes

Current behavior: While on the enrollment confirmation page, if a consumer hits tab and then enter, they can by pass the continue button which is disabled until the primary signs their name.

New behavior: This fix will prevent the consumer from being able to skip the continue button.

# Environment Variable

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. Please share the name of the variable below that would enable/disable the feature and which client it applies to.

Variable name:

- [ ] DC
- [ ] ME

2023-04-20 21:39 UTC, jayreddy519 submitted a review, later dismissed
LGTM.

2023-04-21 14:05 UTC, vkghub requested changes

2023-04-21 14:05 UTC, vkghub commented on app/assets/javascripts/application.js.erb
> +  if(event.code === "Tab") {
- As per this new code, tab feature is completely disabled for this page.
- Tab should not be disabled and user should also be able to navigate through the page using this feature.

2023-04-25 17:15 UTC, vkghub approved these changes
LGTM

2023-04-25 17:16 UTC, jayreddy519 approved these changes

2023-04-25 17:29 UTC, merged