include created_at while cloning evidence histories
ideacrew/enroll pull request #2752
Opened 2023-04-25 17:54 UTC by jacobkagon

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket: Me-184847647

# A brief description of the changes

Current behavior: While looking at evidences, prior evidence histories include incorrect created at dates.

New behavior: evidence histories will include correct created_at timestamp.

# Environment Variable

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. Please share the name of the variable below that would enable/disable the feature and which client it applies to.

Variable name:

- [ ] DC
- [ ] ME

2023-04-25 18:30 UTC, saikumar9 requested changes

2023-04-26 20:25 UTC, saikumar9 requested changes

2023-04-26 20:25 UTC, saikumar9 commented on components/financial_assistance/app/views/financial_assistance/applications/verifications/_admin_verification_actions.html.erb
> +              <td><%= record.is_a?(Eligibilities::RequestResult) ? record.created_at.in_time_zone('Eastern Time (US & Canada)') : record.date_of_action&.in_time_zone('Eastern Time (US & Canada)') %><
```suggestion
              <td><%= (record.is_a?(Eligibilities::RequestResult) ? record.created_at : record.date_of_action).in_time_zone('Eastern Time (US & Canada)') %></td>
```

2023-04-26 20:36 UTC, saikumar9 submitted a review, later dismissed
Changes look good to me! Nice Job @jacobkagon  👏

2023-04-27 16:25 UTC, saikumar9 approved these changes

2023-04-28 17:46 UTC, harshaellanki requested changes

2023-04-28 18:09 UTC, saikumar9 approved these changes, later dismissed

2023-04-28 18:09 UTC, saikumar9 commented on app/models/eligibilities/verification_history.rb
> +      write_attribute(:date_of_action, DateTime.now)
@jacobkagon Can you add a check to see if the value is already populated here? And only update if the value is blank.

2023-04-28 20:08 UTC, saikumar9 approved these changes

2023-04-28 20:13 UTC, harshaellanki approved these changes

2023-04-28 20:21 UTC, merged