184084119 roster upload
ideacrew/enroll pull request #2757
Opened 2023-04-26 16:05 UTC by Rohithone

# PR Checklist

Please check if your PR fulfills the following requirements
- [ ] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket:  https://www.pivotaltracker.com/n/projects/2481183/stories/184084119

# A brief description of the changes

Current behavior: Timeout Error When Using ER Roster Upload Tool for Senate

New behavior: Added event source to avoid timeout error

# Environment Variable

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. Please share the name of the variable below that would enable/disable the feature and which client it applies to.

Variable name: PROCESS_EVENT_SOURCE_IS_ENABLED'

- [x] DC
- [ ] ME

2023-04-26 20:05 UTC, polographer requested changes

2023-04-27 17:13 UTC, Rohithone commented on Gemfile
> +gem 'aca_entities',       git: 'https://github.com/ideacrew/aca_entities.git', branch: '184084119-roster-upload-channels'
I changed to trunk can you please merge aca_entities PR

2023-04-27 17:14 UTC, Rohithone commented on Gemfile.lock
> +  branch: 184084119-roster-upload-channels
I changed to trunk can you please merge aca_entities PR

2023-04-27 17:14 UTC, Rohithone commented on components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller.rb
> +            file_name = file.original_filename
I added a feature flag, please verify

2023-04-27 17:15 UTC, Rohithone commented on app/event_source/subscribers/file_upload/roster_parser_requested_subscriber.rb
> +    class RosterParserRequestedSubscriber
Updated code, please check

2023-06-23 21:03 UTC, closed without merging