add check to copy quote's osse eligibility
ideacrew/enroll pull request #2799
Opened 2023-05-16 14:59 UTC by RyanEddyIC

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket: 
[101973](https://redmine.priv.dchbx.org/issues/101973)

# A brief description of the changes

Current behavior:
PDO's OSSE eligibility is not copied when broker copies a quote

New behavior:
OSSE eligibility will display correctly after quote is copied.

# Environment Variable

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. Please share the name of the variable below that would enable/disable the feature and which client it applies to.

Variable name:

- [ ] DC
- [ ] ME

2023-05-17 13:16 UTC, harshaellanki submitted a review, later dismissed

2023-05-17 19:17 UTC, nisanthyaganti9 requested changes

2023-05-17 19:17 UTC, nisanthyaganti9 commented on features/brokers/broker_create_hc4cc_quote.feature
> +    And Primary broker should see metal level non bronze options
lines `49-55` can you move these to `background`  to avoid duplicating them in scenarios

2023-05-22 13:32 UTC, nisanthyaganti9 approved these changes

2023-05-22 13:42 UTC, harshaellanki approved these changes

2023-05-22 13:42 UTC, merged