fix copy response evet timestamp bug
ideacrew/enroll pull request #2803
Opened 2023-05-18 20:27 UTC by jacobkagon

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket: ME-185211846

# A brief description of the changes

Current behavior: When copying a new application, the hub calls from the first application do not correctly copy over to the copied evidences of the new application

New behavior: This PR fixes this issue so new applications will have the hub call timestamp of the evidence that was copied over.

# Environment Variable

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. Please share the name of the variable below that would enable/disable the feature and which client it applies to.

Variable name:

- [ ] DC
- [ ] ME

2023-05-22 13:07 UTC, vkghub requested changes

2023-05-22 13:12 UTC, jacobkagon commented on app/models/eligibilities/request_result.rb
> +    field :date_of_action, type: DateTime
@vkghub Sai K didn't want to override the created_at timestamp of the copied request result. He suggested making another field that would capture the created at date

2023-05-22 16:31 UTC, jayreddy519 approved these changes

2023-05-23 21:07 UTC, vkghub approved these changes

2023-05-23 21:07 UTC, vkghub approved these changes

2023-05-23 21:23 UTC, merged