Enable reCAPTCHA on Employer Registration and Broker Registration Forms
ideacrew/enroll pull request #2809
Opened 2023-05-23 19:10 UTC by rahulgudim

# PR Checklist

Please check if your PR fulfills the following requirements
- [X] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [X] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket: https://redmine.priv.dchbx.org/issues/102002

# A brief description of the changes

Current behavior:
Prevent external actors (bots or otherwise) are attempting to create new Employers/Brokers

New behavior:

Add reCAPTCHA to strengthen the Registration pages.

# Feature Flag
For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:
`REGISTRATION_RECAPTCHA_IS_ENABLED`

- [X] DC
- [ ] ME

2023-05-30 12:40 UTC, polographer submitted a review, later dismissed

2023-05-30 17:07 UTC, nks2109 requested changes

2023-06-05 14:26 UTC, nks2109 approved these changes
LGTM

2023-06-05 15:12 UTC, TonyHasIdeas approved these changes
LGTM!

2023-06-05 15:25 UTC, merged