correct sep outside oe text error
ideacrew/enroll pull request #2819
Opened 2023-05-30 19:04 UTC by j1joey

# PR Checklist

Please check if your PR fulfills the following requirements
- [ ] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket: ME-185178380

# A brief description of the changes

Current behavior:

New behavior:

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

2023-05-30 19:36 UTC, jacobkagon requested changes
see comments

2023-05-30 19:36 UTC, jacobkagon commented on components/benefit_markets/db/seedfiles/translations/en/insured.rb
> +  ":en.insured.families.final_sep_outside_open_enrollment_body" => "Open enrollment starts on November 1. To enroll before Open Enrollment, you must qualify for a Special Enrollment Period.",
@j1joey few things. 
1. Do we want to make this change for both DC and ME? If only ME, then we should only change the ME translation.
2. Let's avoid hard coding November 1st. There's probably a Resource Registry setting somewhere that has November 1st. Let's try to use that.

2023-06-01 14:17 UTC, jayreddy519 commented
Branch is RED @j1joey

2023-06-01 14:30 UTC, jacobkagon approved these changes

2023-06-01 14:34 UTC, jacobkagon requested changes
@j1joey small change, but this is the requested text:

 "Open enrollment starts on November 1. To enroll before Open Enrollment, you must qualify for a Special Enrollment Period."

You need to capitalize Open Enrollment and Special Enrollment Period

2023-06-01 15:06 UTC, jacobkagon approved these changes, later dismissed
@j1joey small change, but this is the requested text:

 "Open enrollment starts on November 1. To enroll before Open Enrollment, you must qualify for a Special Enrollment Period."

You need to capitalize Open Enrollment and Special Enrollment Period

2023-06-01 19:32 UTC, jayreddy519 approved these changes

2023-06-01 19:33 UTC, jacobkagon approved these changes

2023-06-02 18:21 UTC, closed without merging