AON 8.1 - upgrade jquery-ui to 1.13.2 version
ideacrew/enroll pull request #2898
Opened 2023-07-05 20:07 UTC by saipraveen18

# PR Checklist

Please check if your PR fulfills the following requirements
- [X] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: https://www.pivotaltracker.com/story/show/185357005

# A brief description of the changes

Current behavior: JQuery-ui version is 1.12.1 which has vulnerability issues.

New behavior: Update JQeury-ui to 1.13.2 to resolve vulnerability issues.

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

2023-07-11 13:40 UTC, TreyE requested changes

2023-07-12 17:24 UTC, TreyE requested changes
Ugh.  So appscan is now flagging the new library as:
https://github.com/ideacrew/enroll/pull/2898/checks?check_run_id=14980393295

Is there any way we can either disable or mitigate this?  Like is there an ignore list for app scan on false positives?

2023-07-12 19:30 UTC, saipraveen18 commented
> Ugh. So appscan is now flagging the new library as: https://github.com/ideacrew/enroll/pull/2898/checks?check_run_id=14980393295
> 
> Is there any way we can either disable or mitigate this? Like is there an ignore list for app scan on false positives?

Trey - i have tried to remove jquery-ui.js file when doing codesweep scanning - couldn't figure out another way to do this. Please review and let me know if the solution provided works.

2023-08-07 13:33 UTC, saikumar9 approved these changes
lgtm!

2023-08-07 13:39 UTC, TreyE approved these changes

2023-08-17 16:27 UTC, merged