AON 4.2 - add authorization for employer datatable(old model reference)
ideacrew/enroll pull request #2925
Opened 2023-07-11 17:44 UTC by saipraveen18

https://www.pivotaltracker.com/story/show/185589188

2023-07-11 20:26 UTC, saikumar9 requested changes

2023-07-11 20:26 UTC, saikumar9 commented on app/models/effective/datatables/employer_datatable.rb
> +        HbxProfilePolicy.new(current_user, nil).employer_index?
This method is just checking if 'hbx_staff' exists in the roles field of the User and does not match with what we have in the controller action(Exchanges::HbxProfilesController#employer_poc).

```suggestion
        current_user&.has_hbx_staff_role?
```

2023-07-11 20:26 UTC, saikumar9 commented on spec/models/effective/datatable/employer_datatable_spec.rb
> +  describe '#authorized?' do
Good test coverage.

2023-07-11 20:50 UTC, saikumar9 approved these changes
lgtm!

2023-07-12 15:11 UTC, vkghub approved these changes

2023-07-12 15:26 UTC, merged