185649245 create new sep eligibility rule
ideacrew/enroll pull request #2966
Opened 2023-07-24 20:10 UTC by jacobkagon

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: ME-185649245

# A brief description of the changes

Current behavior: There is not a SEP eligibility rule in place that takes into account the date that a family shops for plans.

New behavior: This PR creates a new eligibility rule that updates the SEP and Enrollment effective date to be the first of the month after plan shopping if the plan shopping date is greater than the original SEP effective date.

# Feature Flag. The eligibility rule first_of_the_month_plan_shopping is only added to ME context. Shouldn't have impact in DC market.

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

2023-07-25 18:22 UTC, saikumar9 approved these changes, later dismissed
lgtm! Adds new sep rule. Good test coverage.

2023-07-26 13:01 UTC, saikumar9 submitted a review, later dismissed

2023-07-26 14:39 UTC, jayreddy519 approved these changes, later dismissed
LGTM.

2023-07-26 15:00 UTC, vkghub requested changes
- next_poss_effective_date is displayed to admin from view history, I think this value should also be updated to be in sync with effective_on.
- Since this effective_on value is updated through consumer interference, I suggest to use Comment model to record the reason for this update.

2023-07-26 16:32 UTC, vkghub approved these changes
LGTM

2023-07-26 16:36 UTC, saikumar9 approved these changes

2023-07-26 16:36 UTC, merged

2023-07-26 16:44 UTC, jayreddy519 reviewed
LGTM.