set full_medicaid_determination value to nil for auto renewals
ideacrew/enroll pull request #2984
Opened 2023-08-02 16:43 UTC by vkghub

# PR Checklist

Please check if your PR fulfills the following requirements
- [ ] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket:  https://www.pivotaltracker.com/story/show/185681354

# A brief description of the changes

Current behavior:

New behavior:

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

2023-08-02 16:57 UTC, saikumar9 requested changes

2023-08-02 17:54 UTC, vkghub commented on components/financial_assistance/app/domain/financial_assistance/operations/applications/aptc_csr_credit_eligibilities/renewals/renew.rb
> +                renewal_application.full_medicaid_determination = application.full_medicaid_determination unless EnrollRegistry[:enroll_app].setting(:site_key).item == :dc
Got it, I'll go ahead and add new RR setting.

2023-08-04 15:42 UTC, saikumar9 approved these changes
lgtm!

2023-08-07 15:09 UTC, saipraveen18 approved these changes

2023-08-07 15:09 UTC, merged