add validation for child of domestic partner
ideacrew/enroll pull request #3004
Opened 2023-08-08 20:45 UTC by jacobkagon

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: https://www.pivotaltracker.com/n/projects/2640060/stories/185698165

# A brief description of the changes

Current behavior: If an applicant is a child and their parent has a domestic partner, there is no validation preventing application submission if that child's relationship to the domestic partner is something other than child of domestic partner.

New behavior: We add a validation to prevent application submission if there is an incorrect relationship between a child and a domestic partner.

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name: **EnrollRegistry.feature_enabled?(:mitc_relationships)**
 
- [x] DC
- [x] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

2023-08-10 15:16 UTC, jayreddy519 submitted a review, later dismissed
lgtm.

2023-08-11 16:49 UTC, saikumar9 requested changes

2023-08-11 17:09 UTC, saikumar9 approved these changes

2023-08-11 17:17 UTC, jayreddy519 approved these changes

2023-08-11 18:10 UTC, merged