set aasm_state to applicant_update_required when missing relationship
ideacrew/enroll pull request #3016
Opened 2023-08-10 21:16 UTC by 4till2

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: TT6-185799081

# A brief description of the changes

Current behavior:

New behavior:

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

2023-08-10 22:23 UTC, 4till2 commented on components/financial_assistance/app/domain/financial_assistance/operations/applications/aptc_csr_credit_eligibilities/renewals/renew.rb
> +                  Failure("Renewal Application: (#{renewal_application.hbx_id}) failed with aasm_state: (#{renewal_application.aasm_state}), because: (#{@failure_reason || 'Unknown'})")
More verbose failure message to provide details around the cause behind a failed renewal beyond the aasm_state.

2023-08-10 22:23 UTC, 4till2 commented on components/financial_assistance/spec/domain/financial_assistance/operations/applications/aptc_csr_credits/renewals/renew_spec.rb
> +        expect(@result.failure).to match(/Renewal Application:.*failed with aasm_state: \(income_verification_extension_required\)/)
To match the updated failure message

2023-08-10 22:24 UTC, 4till2 commented on components/financial_assistance/app/domain/financial_assistance/operations/applications/aptc_csr_credit_eligibilities/renewals/renew.rb
> +              return Failure("Unable to create renewal application - #{application.failure} with params: (#{validated_params})") if application.failure?
More verbose message

2023-08-11 18:01 UTC, saikumar9 requested changes

2023-08-11 19:38 UTC, saikumar9 approved these changes
lgtm!

2023-08-11 19:57 UTC, mdkaraman approved these changes
Awesome job.  Improves error logging overall and moves the affected apps into a more appropriate state.

2023-08-11 19:58 UTC, merged