fail cv3 family transform if enrollment transform fails
ideacrew/enroll pull request #3044
Opened 2023-08-21 20:29 UTC by mdkaraman

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: TT6-185843825

# A brief description of the changes

Current behavior:
Errors caught in the CV3 HbxEnrollment transform are not returned wrapped in a Failure monad.  The CV3 Family transform always unwraps the result of the CV3 HbxEnrollment transform, which throws an exception if the enrollment transform returns failure.  

New behavior:
CV3 HbxEnrollment transform wraps rescued exceptions in a Failure monad.  The CV3 Family transform checks the result of each enrollment transform and returns failure if any enrollments fail the CV3 HbxEnrollment transform.

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name: n/a

- [ ] DC
- [ ] ME

# Additional Context

Adding the @family_hbx_id variable in the CV3 Family transform makes the family hbx id available to other methods that may find it useful for logging purposes.

Removing the logger line and puts statement from the CV3 HbxEnrollment transform is intentional.  The error message is now being bubbled up and should be logged when the CV3 Family transform returns failure.

2023-08-21 21:01 UTC, 4till2 approved these changes, later dismissed
Looks good! Returns a Failure instead of true in the exception. Includes tests.

2023-08-22 13:23 UTC, 4till2 approved these changes

2023-08-22 17:08 UTC, saikumar9 requested changes

2023-08-22 17:39 UTC, mdkaraman commented on app/domain/operations/transformers/family_to/cv3_family.rb
> +          transformed_enrollments.map(&:value!)
Notes from our call about this:
- it makes sense to refactor the construct_payload method to fail the whole operation as soon as a sub-transform step fails (to increase performance of the Family transform)
- for each sub-transform, it's ok to log all failures as long as we return a Failure that will halt the entire CV3 transform (to be sure we log relevant info for debugging)

2023-08-22 17:44 UTC, saikumar9 approved these changes

2023-08-22 17:59 UTC, merged