refactor success and failure for ineligibility ntoice event
ideacrew/enroll pull request #3064
Opened 2023-08-24 19:05 UTC by RyanEddyIC

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: 
[185843838](https://www.pivotaltracker.com/n/projects/2659995/stories/185843838)

# A brief description of the changes

Current behavior:
No failure message on failed initialize application operation

New behavior:
Success and Failure results added

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

2023-08-24 20:11 UTC, scaustin34 submitted a review, later dismissed

2023-08-24 21:23 UTC, polographer commented on components/financial_assistance/app/domain/financial_assistance/operations/applications/verifications/publish_faa_total_ineligibility_notice.rb
> +            parsed_payload = JSON.parse(application.eligibility_response_payload, symbolize_names: true)
can we write a test for this ?

2023-08-25 13:28 UTC, polographer requested changes

2023-08-25 13:28 UTC, polographer commented on components/financial_assistance/app/domain/financial_assistance/operations/applications/verifications/publish_faa_total_ineligibility_notice.rb
>            def construct_payload(application)
can we write a test for this ?

2023-08-25 14:31 UTC, polographer approved these changes, later dismissed

2023-08-25 14:36 UTC, scaustin34 submitted a review, later dismissed

2023-08-25 15:33 UTC, scaustin34 approved these changes

2023-08-25 15:33 UTC, polographer approved these changes

2023-08-25 15:48 UTC, merged