set default configs for moneyrails gem
ideacrew/enroll pull request #3101
Opened 2023-09-01 15:14 UTC by RyanEddyIC

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: 
[185957475](https://www.pivotaltracker.com/n/projects/2659995/stories/185957475)

# A brief description of the changes

Current behavior:
We currently see a large number of warning messages in our logs about default configuration changing in a new version of the MoneyRails gem.

New behavior:
Setting the default global config for the gem will remove these warnings.

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

2023-09-07 19:59 UTC, rahulgudim approved these changes, later dismissed
LGTM!

2023-09-11 21:39 UTC, polographer requested changes
this fixes the warnings when we run the specs on locals and on the main app, however it doesn't fix the warnings (and the future errors) on the engines (/components); TL:DR; we need to add this config on all the initializers of the /components 

See this example; is the spec result of this PR for financial assistance
https://github.com/ideacrew/enroll/actions/runs/6111470551/job/16586794243 

<img width="1825" alt="image" src="https://github.com/ideacrew/enroll/assets/350422/f22df88b-110d-424c-86c8-90cbef7f1c5b">

----

quick edit, we may not need it on all engines, only the ones that actually have the gem... sorry

2023-09-15 17:08 UTC, polographer approved these changes

2023-09-18 15:21 UTC, rahulgudim approved these changes
LGTM

2023-09-21 17:00 UTC, merged