handling error message and rendering it properly
ideacrew/enroll pull request #3213
Opened 2023-09-28 15:35 UTC by nks2109

# PR Checklist

Please check if your PR fulfills the following requirements
- [ ] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: 

# A brief description of the changes

Current behavior:

New behavior:

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

2023-10-04 15:07 UTC, polographer approved these changes

2023-10-04 15:09 UTC, polographer requested changes

2023-10-04 15:09 UTC, polographer commented on components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller.rb
> +              flash[:notice] = 'File uploaded to S3'
can you change this to be "File uploaded, will process it on the background" and move this to the translations file

2023-10-04 15:09 UTC, polographer requested changes

2023-10-04 15:09 UTC, polographer commented on components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller.rb
> +              flash[:notice] = 'File not uploaded to S3'
Can you change this to "There was an error on the upload, please try again" and move the string to the translations file

2023-11-08 19:02 UTC, utkarsh7989 approved these changes
LGTM

2023-11-09 18:31 UTC, polographer approved these changes

2023-11-13 16:31 UTC, merged