Improve performance of Financial Assistance Application Page
ideacrew/enroll pull request #3252
Opened 2023-10-09 16:01 UTC by TreyE

# PR Checklist

Please check if your PR fulfills the following requirements
- [X] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: https://www.pivotaltracker.com/story/show/186206315

# A brief description of the changes

Current behavior: On some individuals the application index page is very slow.

New behavior:  Add additional code to cache and reduce query amounts on the application index page.

2023-10-10 19:05 UTC, saikumar9 requested changes
Please review my comments.

2023-10-10 19:05 UTC, saikumar9 commented on components/financial_assistance/spec/models/financial_assistance/application_spec.rb
> +RSpec.describe ::FinancialAssistance::Application, "with correct index definitions", type: :model, dbclean: :after_each do
Good test coverage to verify indexes.

2023-10-10 19:07 UTC, TreyE commented on components/financial_assistance/app/domain/financial_assistance/operations/applications/query_filtered_applications.rb
> +      class QueryFilteredApplications
Yeah, I was trying to avoid creating a contract as an extra step, I can add it and split out the items.

2023-10-10 19:08 UTC, TreyE commented on components/financial_assistance/app/models/financial_assistance/application.rb
> +# Below you will see a large number of ignored indexes.
Will do.

2023-10-10 19:11 UTC, saikumar9 commented on components/financial_assistance/app/domain/financial_assistance/operations/applications/query_filtered_applications.rb
> +      class QueryFilteredApplications
We do not need a contract to verify these 2 attributes. We can validate this within the same class but in a separate method.

2023-10-11 13:44 UTC, saikumar9 approved these changes
Improves Performace!

2023-10-11 14:19 UTC, saipraveen18 approved these changes

2023-10-11 14:19 UTC, merged