recalculates aptc on thank you page when user clicks browser back
ideacrew/enroll pull request #3284
Opened 2023-10-23 17:49 UTC by saipraveen18

# PR Checklist

Please check if your PR fulfills the following requirements
- [X] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [X] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or updated version)

# What is the ticket # detailing the issue?

Ticket:  https://www.pivotaltracker.com/story/show/185126399

# A brief description of the changes

Current behavior: APTC is not being appropriately applied when user first lands on the Plan shopping thank you page clicks back browser, and then selects the same plan again

New behavior: Display the correct APTC on the thank you page when user clicks back browser button and again comes to thank you page.

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable to initialize the state of the flag. Please share the name of the environment variable below that would turn on/off the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

2023-10-23 20:39 UTC, saikumar9 requested changes
Please review the notes.

2023-10-23 20:39 UTC, saikumar9 commented on app/controllers/insured/plan_shoppings_controller.rb
> +             return if session[:max_aptc].to_f.zero?
@saipraveen18 Did you mean to return nil or 0.0?

2023-10-23 20:39 UTC, saikumar9 commented on app/controllers/insured/plan_shoppings_controller.rb
> +             session[:elected_aptc] = elected_aptc.to_f
```suggestion
             percentage * max_aptc
```

2023-10-24 14:06 UTC, vkghub submitted a review, later dismissed

2023-10-24 16:13 UTC, saikumar9 approved these changes
lgtm!

2023-10-24 17:53 UTC, vkghub approved these changes

2023-10-24 17:53 UTC, merged