add restrictions to verification upload documents
ideacrew/enroll pull request #3361
Opened 2023-12-06 15:19 UTC by rahulgudim

# PR Checklist

Please check if your PR fulfills the following requirements
- [X] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [X] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: 
https://www.pivotaltracker.com/n/projects/2640063/stories/186580953
https://www.pivotaltracker.com/n/projects/2640063/stories/186581001
https://www.pivotaltracker.com/n/projects/2640063/stories/186581070

# A brief description of the changes

Current behavior:
Below Security issues were identified from Mandiant when uploading Verification Documents.

- Macro enabled documents can be uploaded.
-  Any file types can be uploaded.
- Files of any size can be uploaded.

New behavior:
We are going to add some restrictions to the current behavior.

- No macro enabled documents can be uploaded.
- only jpeg, png, pdf files can be uploaded through UI and API.
- Restrict the file size to 100MB.

When any of them violates issue a error message to the user. These restrictions now exist in UI and in API. 

**When a file size exceeds the limit.**

<img width="700" alt="Screenshot 2023-12-06 at 9 14 37 AM" src="https://github.com/ideacrew/enroll/assets/118293805/3abc2de9-0e76-4880-b7b6-44a3036a72fb">

**When an mp4 file or mp4.jpeg file is uploaded**

<img width="700" alt="Screenshot 2023-12-06 at 9 18 40 AM" src="https://github.com/ideacrew/enroll/assets/118293805/d4770c5f-0bab-4235-aa76-45ccdb718780">

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

2023-12-07 15:26 UTC, RyanEddyIC approved these changes

2023-12-07 16:24 UTC, RyanEddyIC approved these changes, later dismissed

2023-12-11 16:07 UTC, polographer approved these changes

2023-12-11 16:13 UTC, polographer requested changes

2023-12-11 16:13 UTC, polographer commented on app/models/vlp_document.rb
> +  ID_FILE_SIZE_MB = 100
can we make this a feature flag ?

2023-12-11 16:15 UTC, polographer requested changes

2023-12-11 16:15 UTC, polographer commented on app/models/vlp_document.rb
> +  ALLOWED_MIME_TYPES = %w[image/png image/jpeg application/pdf].freeze
probably this one too, add the valuie as defaults

2023-12-11 22:06 UTC, polographer approved these changes

2023-12-11 22:12 UTC, utkarsh7989 approved these changes

2023-12-11 22:28 UTC, merged