creates broker agency staff role if person matches during broker registration
ideacrew/enroll pull request #3437
Opened 2024-01-04 03:05 UTC by saikumar9

# PR Checklist

Please check if your PR fulfills the following requirements
- [ ] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes/features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or updated version)

# What is the ticket # detailing the issue?

Ticket: [IVL Product Development - 186693256](https://www.pivotaltracker.com/story/show/186693256)

# A brief description of the changes

Current behavior:

New behavior:

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

2024-01-06 00:49 UTC, saikumar9 commented on components/benefit_sponsors/app/models/benefit_sponsors/organizations/factories/profile_factory.rb
> +          def create_broker_agency_staff_role(bap_id)
That is correct.

2024-01-06 00:50 UTC, saikumar9 commented on components/benefit_sponsors/app/models/benefit_sponsors/organizations/factories/profile_factory.rb
> +          def create_broker_agency_staff_role(bap_id)
Good Catch! I will get that fixed.

2024-01-08 14:33 UTC, TreyE requested changes
Please note comments in the factory.

2024-01-08 14:33 UTC, TreyE commented on components/benefit_sponsors/app/models/benefit_sponsors/organizations/factories/profile_factory.rb
> +                benefit_sponsors_broker_agency_profile_id: bap_id
Small issue here.  By setting the state directly as active and skipping the transition, we skip a number of pieces of code which would send invitations or notifications, as well as record some auditable data about the transition.

The most import is the transition under the broker agency staff role itself:
`event :broker_agency_accept, :after => [:record_transition, :send_invitation]`

We either need to trigger the transition or invoke these methods ourselves in order to keep both the database and the invitation/notification behaviour consistent.

2024-01-08 14:46 UTC, TreyE approved these changes

2024-01-08 14:48 UTC, saipraveen18 approved these changes

2024-01-08 14:48 UTC, merged