fix pay online redirect
ideacrew/enroll pull request #3456
Opened 2024-01-09 16:08 UTC by rahulgudim

# PR Checklist

Please check if your PR fulfills the following requirements
- [X] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [X] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: https://redmine.priv.dchbx.org/issues/103912

# A brief description of the changes

Current behavior:

When Pay Online button is hit from employer page in Billing screen the SSO token gets timed out (as it is generated when the page is loaded) and it redirects back to Enroll App instead of SSO screen.

New behavior:
Initiate a SSO token when user hits the Pay Online button instead when page is loaded so the token does not time out and user gets redirected to wellsfargo SSO page for further payment.

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

2024-01-10 17:20 UTC, RyanEddyIC submitted a review, later dismissed

2024-01-11 20:22 UTC, polographer approved these changes

2024-01-11 20:33 UTC, polographer requested changes

2024-01-11 20:33 UTC, polographer commented on components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/accounts/_pay_online_confirmation_modal.html.erb
> +        <button class="btn btn-default pay_online_confirmation pull-right left-margin" id="pay-online-confirmation-final">Pay Online</button>
"Pay online" should be on the translation file

2024-01-11 20:33 UTC, polographer commented on components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/accounts/_pay_online_confirmation_modal.html.erb
> +        <span class="btn btn-default btn-small" data-dismiss="modal">Cancel</span>
"Cancel" should be on the translation file

2024-01-11 22:29 UTC, polographer submitted a review, later dismissed

2024-01-11 23:04 UTC, RyanEddyIC submitted a review, later dismissed

2024-01-12 14:58 UTC, polographer approved these changes

2024-01-12 15:07 UTC, RyanEddyIC approved these changes

2024-01-12 15:29 UTC, merged