add pundit policy for evidences and documents
ideacrew/enroll pull request #3562
Opened 2024-02-14 12:53 UTC by vkghub

# PR Checklist

Please check if your PR fulfills the following requirements
- [ ] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: 

# A brief description of the changes

Current behavior:

New behavior:

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

2024-02-16 21:17 UTC, TreyE requested changes
Please place the policies for resources in the appropriate engine.  For example, because these policies enforce for items in the Financial Assistance, they should be in that engine.

**Reply ->** Even though financial assistance VerificationDocumentsController is the part of engine, it uses Document and Evidence model from main app to process the request. Since these models are in main app I created policies in main app.

2024-02-18 17:01 UTC, TristanB17 approved these changes

2024-02-18 18:00 UTC, ymhari approved these changes

2024-02-18 18:47 UTC, ymhari approved these changes

2024-02-19 23:19 UTC, TreyE approved these changes

2024-02-20 01:54 UTC, merged