Clean up possible XSS injections vectors which rely on "#html_safe"
ideacrew/enroll pull request #3581
Opened 2024-02-18 19:01 UTC by TreyE

https://www.pivotaltracker.com/story/show/187054498

2024-02-20 14:35 UTC, saikumar9 requested changes
@treye A couple of nitpicks regarding this PR.
- Please delete app/models/concerns/sanitize_concern.rb and spec/models/concerns/sanitize_concern_spec.rb as we are now using html_scrubber_util.rb.
- Add some YARD(inline in code) documentation in lib/html_scrubber_util.rb similar to app/models/concerns/sanitize_concern.rb for others to understand what it is used for.
- I also suggest you add some YARD(inline in code) for the new Brakeman check you added maybe in `checks/html_safe_usage_check.rb`.
- Fix indentation in `app/views/shared/_alph_paginate.html.erb`

2024-02-21 17:12 UTC, kristinmerbach reviewed
Looks good! A couple minor comments, but nothing big.

**Note**: because of focus of PR and number of views touched, do not think the many instances of copy not in translations being left as is should not be a blocker for getting this fix in

2024-02-21 17:56 UTC, saikumar9 approved these changes
Looks good to me once Kristin's comments are addressed.

2024-02-22 16:10 UTC, kristinmerbach approved these changes

2024-02-22 16:33 UTC, merged