admin autolock feature
ideacrew/enroll pull request #3703
Opened 2024-03-21 20:13 UTC by jacobkagon

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes/features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update to a version)

# What is the ticket # detailing the issue?

Ticket: [ME-186972348](https://www.pivotaltracker.com/n/projects/2640060/stories/186972348)

# A brief description of the changes

Current behavior: N/A

New behavior: If an admin account is expired for more than a set period of days, we will mark their account as expired

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name: ADMIN_ACCOUNT_AUTOLOCK_IS_ENABLED

- [ ] DC
- [x] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

2024-03-26 00:29 UTC, TreyE requested changes
Minor change to how we test for the presence of an hbx_staff_role - otherwise good.

2024-03-26 00:29 UTC, TreyE commented on app/models/concerns/authorization_concern.rb
> +      return false unless roles.include?("hbx_staff") && EnrollRegistry.feature_enabled?(:admin_account_autolock)
This isn't typically how we test for the presence of an admin role.

We usually check to see if the user has an associated person, then to see if that person has an associated and active hbx_staff_role.  There might even be a helper method I think.

2024-04-02 16:53 UTC, jayreddy519 approved these changes
updated code to check person has an associated and active hbx_staff_role.

good test coverage, looks good to me .

2024-04-04 21:53 UTC, TreyE approved these changes

2024-04-04 22:33 UTC, merged