add respond_to protections for broker agency registrations controller
ideacrew/enroll pull request #3759
Opened 2024-04-22 17:14 UTC by TristanB17

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes/features)

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update to a version)

# What is the ticket # detailing the issue?

Ticket: https://www.pivotaltracker.com/story/show/187465541

# A brief description of the changes

Current behavior: several endpoints (create, edit, counties_by_zip_code) will respond to invalid request types

New behavior:  fixes several endpoints to only respond to certain request types

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

2024-04-22 19:06 UTC, ymhari submitted a review, later dismissed

2024-04-25 15:00 UTC, ymhari submitted a review, later dismissed

2024-04-26 21:28 UTC, vkghub requested changes

2024-04-26 21:28 UTC, vkghub commented on components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/registrations_controller.rb
> +        respond_to do |format|
- Request type is already handled in route config **resource_not_found**, this is not needed here. 
- can you revert this logic?

2024-04-29 14:30 UTC, vkghub approved these changes
LGTM

2024-04-29 15:58 UTC, ymhari approved these changes

2024-04-29 15:58 UTC, merged