Support and glossary texts
ideacrew/enroll pull request #377
Opened 2021-05-24 16:05 UTC by eidarus

### Master Redmine ticket
* (Required!)

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2021-05-24 20:03 UTC, bill-transue requested changes
It looks like out of pocket costs may be the only glossary item with a different term and title. Please double check the `FinancialAssistance::Benefit::INSURANCE_TYPE` one.

2021-05-24 20:15 UTC, ZASMan commented on components/financial_assistance/app/views/financial_assistance/shared/_consumer_fields.html.erb
> +      <label>Is this person a member of an <%= render partial:"shared/glossary", locals: {key: "american_indian", title: "American Indian", term: "American Indian" } %> or <%= render partial:"shared/
Sometimes the title and term is the same?

2021-05-24 20:19 UTC, eidarus commented on components/financial_assistance/app/views/financial_assistance/deductions/index.html.erb
> +              <%= render partial:"shared/glossary", locals: {key: "#{deduction_kind.to_sym}", title: "#{FinancialAssistance::Benefit::INSURANCE_TYPE[deduction_kind.to_sym]}", term: "#{FinancialAssist
`FinancialAssistance::Deduction::DEDUCTION_TYPE[deduction_kind.to_sym]` returns a full statement from components/financial_assistance/app/models/financial_assistance/deduction.rb, I just wanted the key it was using to pick which statement to return, and then I'm using that to grab the appropriate translation

2021-05-24 21:13 UTC, bill-transue commented on components/financial_assistance/app/views/financial_assistance/deductions/index.html.erb
> +              <%= render partial:"shared/glossary", locals: {key: "#{deduction_kind.to_sym}", title: "#{FinancialAssistance::Benefit::INSURANCE_TYPE[deduction_kind.to_sym]}", term: "#{FinancialAssist
👍🏼

2021-05-25 12:39 UTC, bill-transue approved these changes
Good work @eidarus, this will move the glossary to translations meaning they will be much easier to change and allow for client control.

2021-05-26 14:51 UTC, merged