enforce mime types for endpoints
ideacrew/enroll pull request #3770
Opened 2024-04-23 19:28 UTC by ymhari

# PR Checklist

Please check if your PR fulfills the following requirements
- [X] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit)
- [X] Tests for the changes have been added (for bugfixes/features), they use let helpers and before blocks
- [ ] For all UI changes, there is cucumber coverage
- [ ] Any endpoint touched in the PR has an appropriate Pundit policy. For open endpoints, reasoning is documented in PR and code
- [ ] For all scripts or rake tasks, how to run it is documented on both the PR and in the code
- [ ] There are no inline styles added
- [ ] There are no inline javascript added
- [ ] There is no hard coded text added/updated in helpers/views/Javascript. New/updated translation strings do not include markup/styles, unless there is supporting documentation
- [ ] Code does not use .html_safe
- [ ] All images added/updated have alt text
- [X] Doesn’t bypass rubocop rules in any way

# PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update to a version)

# What is the ticket # detailing the issue?

Ticket: https://www.pivotaltracker.com/story/show/187465810

# A brief description of the changes

Current behavior: does not enforce mime type for some endpoints

New behavior: enforcing mime type for missing endpoints

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

2024-04-23 21:34 UTC, TristanB17 commented on app/controllers/insured/consumer_roles_controller.rb
> +    end
I believe if there's not a specific target for the `render` action, this respond_to block can be written as 
```
respond_to :html
```

2024-04-23 21:35 UTC, TristanB17 approved these changes, later dismissed
LGTM! Just added a single optional comment, not necessary to update PR

2024-04-24 00:57 UTC, vkghub requested changes
One more method is missing 
- https://github.com/ideacrew/enroll/pull/3770/files#diff-2a0aa5303b979e3a8f8e489305be1c81a26dfb6538b8510cf1ac4e25e62a2401R145
- build_insured_consumer_role_index_path

2024-04-25 17:35 UTC, desireB approved these changes
I confirm that protect_from_forgery is present in https://github.com/ideacrew/enroll/blob/trunk/app/controllers/application_controller.rb L24, with no exception. This is indeed a false positive.

2024-04-29 18:52 UTC, vkghub approved these changes

2024-05-02 14:33 UTC, TristanB17 approved these changes

2024-05-02 16:54 UTC, merged