create demographics group and alive status on person create
ideacrew/enroll pull request #3814
Opened 2024-05-10 02:44 UTC by TristanB17

# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit)
- [x] Tests for the changes have been added (for bugfixes/features), they use let helpers and before blocks
- [ ] For all UI changes, there is cucumber coverage
- [ ] Any endpoint touched in the PR has an appropriate Pundit policy. For open endpoints, reasoning is documented in PR and code
- [ ] Any endpoint modified in the PR only responds to the expected MIME types.
- [ ] For all scripts or rake tasks, how to run it is documented on both the PR and in the code
- [ ] There are no inline styles added
- [ ] There are no inline javascript added
- [ ] There is no hard coded text added/updated in helpers/views/Javascript. New/updated translation strings do not include markup/styles, unless there is supporting documentation
- [ ] Code does not use .html_safe
- [ ] All images added/updated have alt text
- [ ] Doesn’t bypass rubocop rules in any way

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update to a version)

# What is the ticket # detailing the issue?

Ticket: https://www.pivotaltracker.com/story/show/187563276

# A brief description of the changes

Current behavior: person and consumer role are created simultaneously during sign up + adding a family member

New behavior: demographics group and alive status are now generated after a consumer role is generated for a person

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [x] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

2024-05-16 15:51 UTC, vkghub requested changes

2024-05-16 15:51 UTC, vkghub commented on app/domain/operations/families/create_member.rb
> +        person.create_demographics_group
adding here will update person record again. Lets move this to the operation: **app/domain/operations/people/transform_applicant_to_member.rb** and use the pattern present in this operation.

2024-05-16 15:51 UTC, vkghub commented on app/models/person.rb
> +    return unless demographics_group.blank?
Sine this feature is currently only for consumer role, it is better to add one more check to verify if the person has consumer role.

2024-05-20 13:40 UTC, ymhari requested changes

2024-05-20 13:40 UTC, ymhari commented on app/models/person.rb
> +    demographics_group = DemographicsGroup.new(alive_status: AliveStatus.new)
Create alive status in a different method, and check the presence of the alive status before create a new one.

2024-05-21 16:37 UTC, vkghub approved these changes
LGTM

2024-05-21 20:42 UTC, ymhari approved these changes

2024-05-21 21:01 UTC, merged