bs4 plan shopping vs clean bootstrap branch
ideacrew/enroll pull request #3821
Opened 2024-05-10 21:26 UTC by scaustin34

# PR Checklist

Please check if your PR fulfills the following requirements
- [ ] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit)
- [ ] Tests for the changes have been added (for bugfixes/features), they use let helpers and before blocks
- [ ] For all UI changes, there is cucumber coverage
- [ ] Any endpoint touched in the PR has an appropriate Pundit policy. For open endpoints, reasoning is documented in PR and code
- [ ] Any endpoint modified in the PR only responds to the expected MIME types.
- [ ] For all scripts or rake tasks, how to run it is documented on both the PR and in the code
- [ ] There are no inline styles added
- [ ] There are no inline javascript added
- [ ] There is no hard coded text added/updated in helpers/views/Javascript. New/updated translation strings do not include markup/styles, unless there is supporting documentation
- [ ] Code does not use .html_safe
- [ ] All images added/updated have alt text
- [ ] Doesn’t bypass rubocop rules in any way

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update to a version)

# What is the ticket # detailing the issue?

Ticket: 

# A brief description of the changes

Current behavior:

New behavior:

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

2024-05-20 21:32 UTC, charlienparker commented on app/views/shared/_plan_shopping_progress.html.erb
> +<% ridp = (defined? ridp) ? ridp : false %>
are either `continue_disabled` or `ridp` being used here? If not, I think we can remove them...

and if we do remove them, I'm thinking this partial ends up looking exactly like the `consumer_signup` partial we have, save for the "title" label. would it be worth combining these two partials into one "progress_nav" partial or something to that effect?

2024-05-20 21:44 UTC, charlienparker requested changes

2024-05-20 21:44 UTC, charlienparker commented on app/views/insured/family_members/index.html.erb
> +    <%= render partial: "shared/progress_navigation_buttons", locals: {previous_style: "outline", next_link: url } %>
we can probably remove the previous_style argument here - it defaults to "outline" in the partial

2024-05-20 21:44 UTC, charlienparker commented on app/helpers/navigation_helper.rb
> +  def family_info_progress_hash
this def is repeated from the above

2024-05-21 16:39 UTC, scaustin34 commented on app/helpers/navigation_helper.rb
> +  def family_info_progress_hash
all good catches, thanks!

2024-05-21 19:12 UTC, charlienparker approved these changes

2024-05-21 19:12 UTC, charlienparker commented on app/helpers/navigation_helper.rb
>    def sign_up_nav_options
nitpick - can we move this def above the progress_hash helpers? maybe even add comments marking which of these defs belong to the signup flow and which of these defs belong to the coverage experiences? just a little jarring to me to have sign_up_nav_options be between a bunch of defs for a separate experience...

2024-05-22 21:13 UTC, charlienparker approved these changes

2024-05-22 21:13 UTC, charlienparker commented on app/controllers/insured/family_members_controller.rb
> +    @bs4 = true if params[:bs4] === "true"
is triple equals intended here?

2024-05-24 15:21 UTC, kristinmerbach requested changes
Tried this locally and the progress menu for the consumer signup ended up messed up, can you please look into?

Also, looks like Add New Member button loads in the form using not @bs4 so looks very wonky on the page

2024-05-24 15:21 UTC, kristinmerbach commented on db/seedfiles/translations/en/me/shared.rb
> +    "en.support_texts.help_me_decide" => "<b>Who else should I include in my household? </b> <br> <br> If you file a federal tax return, include the following people. Include everyone on this list ev
We should not be adding to the markup in translation issue, please separate out.

2024-05-24 15:21 UTC, kristinmerbach commented on app/views/ui-components/v1/modals/_detail_modal.html.erb
> +      <div class="modal-header" style="border-bottom: none">
no inline styles please, use `border-bottom-0` class

2024-05-24 15:21 UTC, kristinmerbach commented on app/views/ui-components/bs4/v1/navs/_header.html.erb
> +    <a class="navbar-brand mr-0" href="#" title="home page link">
title should be in translation

2024-05-24 15:21 UTC, kristinmerbach commented on app/views/shared/_shop_for_plans_progress.html.erb
> +    Plan Selection
text into translation here and for the other bullets as well

2024-05-24 15:21 UTC, kristinmerbach commented on app/views/shared/_sep_shop_for_plans_progress.html.erb
> +    <%= h(link_to 'Waive Coverage', '#', data: {toggle: "modal", target: "#waive_confirm"}, class: 'btn btn-waive btn-default') %>
waive coverage to translation

2024-05-24 15:21 UTC, kristinmerbach commented on app/views/shared/_sep_shop_for_plans_progress.html.erb
> +    Special Enrollment Period
bullets to translations

2024-05-24 15:21 UTC, kristinmerbach commented on app/views/shared/_consumer_home_address_fields.html.erb
> +      <span tabindex="0" onkeydown="handleButtonKeyDown(event, 'add_mailing_address')" id="add_mailing_address" class="mb-4 form-action btn-secondary <%= pundit_class Family, :updateable?%>">Add Mail
this has been reworked as pr currently in review, verify these changes against that

2024-05-28 18:27 UTC, scaustin34 commented on db/seedfiles/translations/en/dc/shared.rb
> +    "en.support_texts.help_me_decide" => "<b>Who else should I include in my household? </b> <br> <br> If you file a federal tax return, include the following people. Include everyone on this list ev
leaving this for now as its hooked into the 'not sure' modals that use a shared partial that dynamically pulls the text based on the translation key. Will need to figure out a solution for this in the future.

2024-05-30 17:50 UTC, kristinmerbach approved these changes
Very minor changes, though it would be good if you could look into the XSS warnings throughout

2024-05-30 17:50 UTC, kristinmerbach commented on app/views/insured/family_members/_family_members.html.erb
> +    <h3><%= @sep.title %> on: <%= @sep.qle_on %></h3>
really minor, but on should be in a translation

2024-05-30 17:50 UTC, kristinmerbach commented on app/views/insured/family_members/_family_members.html.erb
> +      <%= link_to(main_app.new_insured_family_member_path(:family_id => @family.id, employee_role_id: @employee_role.try(:id), consumer_role_id: @consumer_role.try(:id), bs4: @bs4), :remote => true,
rework to sanitize, i can show you if needed

2024-05-30 17:50 UTC, kristinmerbach commented on app/views/insured/plan_shoppings/show.html.erb
> +                <strong><%= l10n("Please note your final cost may change based on the final enrollment of all employees.") %></strong>
while this is in an l10n, it should be moved to a translation file

2024-05-30 17:50 UTC, kristinmerbach commented on app/views/insured/plan_shoppings/show.html.erb
> +              <a class="btn btn-default ivl-compare-selected-plans-link" href="javascript:void(0);" style="display: none;" data-cuke="ivl-compare-selected-plans-link"
inline style

2024-05-30 17:50 UTC, kristinmerbach commented on app/views/insured/plan_shoppings/show.html.erb
> +              <a class="btn btn-default compare-selected-plans-link" href="javascript:void(0);" style="display: none;"
same as above

2024-05-30 17:50 UTC, kristinmerbach commented on app/views/insured/plan_shoppings/show.html.erb
> +            <div class="col-lg-9 col-md-9 co-sm-9 col-xs-12" id="planContainer" style="padding-right:0">
inline style can just use pr-0

2024-06-03 17:00 UTC, merged