sort seps text sizes
ideacrew/enroll pull request #4686
Opened 2024-10-21 14:45 UTC by kristinmerbach

# PR Checklist

Please check if your PR fulfills the following requirements:
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit)
- [x] Tests for the changes have been added (for bug fixes/features), and they use `let` helpers and `before` blocks.
- [x] For all UI changes, there is Cucumber coverage.
- [x] Any endpoint touched in the PR has an appropriate Pundit policy. For open endpoints, the reasoning is documented in the PR and code.
- [x] Any endpoint modified in the PR only responds to the expected MIME types.
- [x] For all scripts or rake tasks, how to run them is documented in both the PR and the code.
- [x] There are no inline styles added.
- [x] There is no inline JavaScript added.
- [x] There is no hard-coded text added/updated in helpers/views/JavaScript. New/updated translation strings do not include markup/styles unless there is supporting documentation.
- [x] Code does not use `.html_safe`.
- [x] All images added/updated have alt text.
- [x] Does not bypass RuboCop rules in any way.

# PR Type
What kind of change does this PR introduce?:

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix, Migration, or Report (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update to a version)

# What is the ticket # detailing the issue?

Ticket: https://www.pivotaltracker.com/story/show/188449005

# A brief description of the changes:

Current behavior: The top section of the SEPs (the common ones) didn't have a distinct header, just the label for the field, so visually it seemed less highlighted.

New behavior: A header for the most common SEPs was separated out at the same level as the least common header.

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and indicate which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

2024-10-21 14:49 UTC, TristanB17 submitted a review, later dismissed

2024-10-21 15:12 UTC, charlienparker requested changes, later dismissed

2024-10-21 18:59 UTC, kristinmerbach commented on app/views/exchanges/manage_sep_types/_display_by_market.html.erb
> +          <section>
change made!

2024-10-22 11:35 UTC, charlienparker approved these changes

2024-10-22 14:46 UTC, TristanB17 approved these changes

2024-10-22 19:00 UTC, merged