display enrollment tax household details on enrollment summary page
ideacrew/enroll pull request #4739
Opened 2024-11-07 18:54 UTC by saipraveen18

# PR Checklist

Please check if your PR fulfills the following requirements:
- [X] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit)
- [X] Tests for the changes have been added (for bug fixes/features), and they use `let` helpers and `before` blocks.
- [ ] For all UI changes, there is Cucumber coverage.
- [ ] Any endpoint touched in the PR has an appropriate Pundit policy. For open endpoints, the reasoning is documented in the PR and code.
- [ ] Any endpoint modified in the PR only responds to the expected MIME types.
- [ ] For all scripts or rake tasks, how to run them is documented in both the PR and the code.
- [ ] There are no inline styles added.
- [ ] There is no inline JavaScript added.
- [ ] There is no hard-coded text added/updated in helpers/views/JavaScript. New/updated translation strings do not include markup/styles unless there is supporting documentation.
- [ ] Code does not use `.html_safe`.
- [ ] All images added/updated have alt text.
- [ ] Does not bypass RuboCop rules in any way.

# PR Type
What kind of change does this PR introduce?:

- [ ] Bugfix
- [X] Feature (requires Feature flag)
- [ ] Data fix, Migration, or Report (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update to a version)

# What is the ticket # detailing the issue?

Ticket: https://www.pivotaltracker.com/story/show/188496814

# A brief description of the changes:

Current behavior: On the Plan summary page, if the Plan has APTC applied, it is becoming difficult for the business to identify which FAA application's APTC was actually used. 

New behavior: To easily identify which FAA application's APTC was used for the Plan, we are displaying Application details and Enrollment tax household details on the Plan summary page.

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and indicate which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context

<img width="1679" alt="Screenshot 2024-11-12 at 9 30 14 AM" src="https://github.com/user-attachments/assets/a95fc6bb-62a7-457a-b4b8-210bb8df8568">

2024-11-12 16:00 UTC, saikumar9 submitted a review, later dismissed
lgtm!

2024-11-13 20:50 UTC, raghuramg commented on app/views/ui-components/v1/cards/_summary.html.erb
> +              <dd><%= thh_enr.household_health_benchmark_ehb_premium || l10n('not_available') %></dd>
you may want use `number_to_currency` helper here, for displaying amounts. same with `household_dental_benchmark_ehb_premium`

2024-11-13 20:54 UTC, raghuramg requested changes
left feedback

2024-11-13 21:25 UTC, saikumar9 approved these changes, later dismissed
LGTM!

2024-11-13 21:26 UTC, raghuramg commented on app/models/hbx_enrollment.rb
> +    thh_enrs.first&.tax_household&.tax_household_group
can we use most recent record...`thh_enrs.last` instead of `thh_enrs.first`. will that make any difference

2024-11-13 21:50 UTC, saikumar9 approved these changes

2024-11-13 21:51 UTC, raghuramg approved these changes
LGTM

2024-11-13 22:10 UTC, merged