Orr head of household
ideacrew/enroll pull request #535
Opened 2021-07-09 13:26 UTC by RyanEddyIC

### Master Redmine ticket
* (Required!)

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2021-07-09 17:48 UTC, ymhari requested changes

2021-07-09 17:48 UTC, ymhari commented on components/ui_helpers/app/views/workflow/step.html.erb
> +            <div class="margin-bottom-30 margin-bottom-adjustment <%= "hide" unless step_enabled?(section) %>">
hide is causing issue when submitting an application.

2021-07-09 17:48 UTC, ymhari commented on components/financial_assistance/lib/schemas/financial_assistance.xsd
> +			<xs:element name="is_filing_as_head_of_household" type="xs:boolean" minOccurs="0"/>
Would not be needing this at the moment as these changes for mitc not haven.

2021-07-09 17:48 UTC, ymhari commented on components/ui_helpers/lib/ui_helpers/workflow_helper.rb
> +    def step_hidden?(line)
Need tests for this helper method.

2021-07-09 17:48 UTC, ymhari commented on components/ui_helpers/lib/ui_helpers/workflow_helper.rb
> +        return FinancialAssistanceRegistry.feature_enabled?(:filing_as_head_of_household) ? "hide filing-as-head-of-household" : "hide"
This may also cause a submission issue please check when the settings are set to false.

2021-07-09 17:48 UTC, ymhari commented on components/financial_assistance/app/models/financial_assistance/applicant.rb
> +      filing_as_head = (FinancialAssistanceRegistry.feature_enabled?(:filing_as_head_of_household) && is_required_to_file_taxes && !is_claimed_as_tax_dependent) ? !is_filing_as_head_of_household.nil?
Add tests with config turned ON and also OFF.

2021-07-09 17:48 UTC, ymhari commented on components/financial_assistance/app/assets/javascripts/financial_assistance/step_conditionals.js
> +  $("#is_required_to_file_taxes_yes, #is_required_to_file_taxes_no, #is_claimed_as_tax_dependent_yes, #is_claimed_as_tax_dependent_no, #is_filing_as_head_of_household_yes, #is_filing_as_head_of_house
Add cucumbers for UI changes.

2021-07-09 17:48 UTC, ymhari commented on components/financial_assistance/app/assets/javascripts/financial_assistance/step_conditionals.js
> +    if ($('#is_joint_tax_filing_yes').is(':checked')) {
Add cucumbers for UI changes.

2021-07-09 17:48 UTC, ymhari commented on components/financial_assistance/app/assets/javascripts/financial_assistance/step_conditionals.js
> +      $('#is_filing_as_head_of_household_yes, #is_filing_as_head_of_household_no').prop('required', false);
Add cucumbers for UI changes.

2021-07-11 19:33 UTC, bill-transue approved these changes
Good work @RyanEddyIC, thanks for making the configs match.

2021-07-11 19:48 UTC, merged