add hugo documentation for starting golden seed locally
ideacrew/enroll pull request #582
Opened 2021-07-21 13:58 UTC by jacobkagon

### Master Pivotal ticket
* https://www.pivotaltracker.com/n/projects/2481179/stories/178952981
### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2021-07-21 14:33 UTC, ZASMan commented on hugo/content/docs/data_seed.md
> +7.  Go to admin dropdown menu and click goldenseed
I think it actually says "Data Seed UI" or something. Double check.

2021-07-22 13:11 UTC, ZASMan requested changes

2021-07-22 13:11 UTC, ZASMan commented on hugo/content/docs/data_seed.md
> +4.  \*Make sure there is enough memory on the server to run both of those commands
there's an extra \ on this line, and you put a *before "make", a single astereik is for italicizing. Did you mean to put the single asteriks around "Make sure"? Maybe do that and get rid of the slash.

2021-07-23 12:18 UTC, ZASMan approved these changes
Thanks for taking care of those!

2021-07-27 14:47 UTC, bill-transue approved these changes
This is great however we also want to document the `rake` task methods, which are faster and more useful for developers. I'll have a separate ticket made for that. Thanks @jacobkagon!

2021-07-27 14:47 UTC, merged