Disable medicaid tax credit links
ideacrew/enroll pull request #597
Opened 2021-07-23 21:31 UTC by jacobkagon

### Master Pivotal ticket
* https://www.pivotaltracker.com/n/projects/2481183/stories/178953781 

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2021-07-28 13:54 UTC, bill-transue requested changes
Minor changes needed to the view but good work overall @jacobkagon.

2021-07-28 13:54 UTC, bill-transue commented on app/views/insured/families/inbox.html.erb
> +<% end %>
This needs to go over line 23 so the `</div>` is conditionally added to the view with the opening `<div>`.

2021-07-28 13:54 UTC, bill-transue commented on app/views/insured/families/verification.html.erb
>  </div>
These lines need to be indented within the `if` block.

2021-07-28 13:54 UTC, bill-transue commented on app/views/insured/families/inbox.html.erb
>    <%= render partial: "navigate_to_curam_for_documents", :locals => {display_text: "If you applied for Medicaid and tax credit savings, view additional messages"} %>
Indent these lines and the closing `</div>` below within the `unless` block.

2021-07-28 15:12 UTC, bill-transue approved these changes
Good work @jacobkagon, this will prevent the medicaid tax credit links from showing up when the feature is turned off.

2021-07-29 21:24 UTC, bill-transue approved these changes
Good work @jacobkagon, this should make the Medicaid tax credit links a configurable item and sets the ME and DC stored configs and the DC committed configs.

2021-08-11 21:04 UTC, jacobkagon commented
The contents of this branch have already been merged into trunk in this PR: https://github.com/ideacrew/enroll/pull/620/

2021-08-11 21:04 UTC, closed without merging