new migration to update thh_member level csr variant
ideacrew/enroll pull request #649
Opened 2021-08-03 19:21 UTC by jayreddy519

### Master Redmine ticket
* (Required!)

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2021-08-04 16:49 UTC, ymhari requested changes

2021-08-04 16:49 UTC, ymhari commented on db/migrate/20210803162052_migrate_thm_csr_variant.rb
> +# rubocop:disable Metrics/CyclomaticComplexity
Avoid disabling Rubocop.

2021-08-04 16:49 UTC, ymhari commented on db/migrate/20210803162052_migrate_thm_csr_variant.rb
> +    people = Person.all
Do we need to loop through all the person records in the system? Guess we can pick on the person the records with existing consumer roles. 
Or instead, we can pick families with tax_households. 
Or pick families which have eligibility determinations are for 2021(I believe the best option here).

2021-08-04 16:49 UTC, ymhari commented on db/migrate/20210803162052_migrate_thm_csr_variant.rb
> +    people.each do |person|
Can loop through the family and also will result in less complexity for the report.

2021-08-04 16:49 UTC, ymhari commented on db/migrate/20210803162052_migrate_thm_csr_variant.rb
> +# frozen_string_literal: true
Any specific reason for the file naming?

2021-08-04 16:49 UTC, ymhari commented on db/migrate/20210803162052_migrate_thm_csr_variant.rb
> +        thhm = latest_tax_household.tax_household_members.where(is_ia_eligible: true)
Add a logger if there is any tax_household without tax_household_members just in case.

2021-08-04 16:49 UTC, ymhari commented on db/migrate/20210803162052_migrate_thm_csr_variant.rb
> +        csr_percent = ed.csr_percent_as_integer
What happens there if there is no eligibility determination?

2021-08-04 16:49 UTC, ymhari commented on db/migrate/20210803162052_migrate_thm_csr_variant.rb
> +# rubocop:enable Metrics/CyclomaticComplexity
Avoid disabling rubocop.

2021-08-04 16:49 UTC, ymhari commented on db/migrate/20210803162052_migrate_thm_csr_variant.rb
> +        puts "No primary_family or active househod or latest_active_household exists for person with the given hbx_id #{person.hbx_id}" unless Rails.env.test?
If at all using this log it in the logger file.

2021-08-04 16:49 UTC, ymhari commented on db/migrate/20210803162052_migrate_thm_csr_variant.rb
> +    @logger = Logger.new("#{Rails.root}/log/migrate_thm_csr_variant.log") unless Rails.env.test?
Good adding logger file.

2021-08-04 17:03 UTC, ymhari requested changes

2021-08-04 17:03 UTC, ymhari commented on db/migrate/20210803162052_migrate_thm_csr_variant.rb
> +            thm.update(csr_percent_as_integer: csr_percent)
Rescue here and log errors if any.

2021-08-04 17:03 UTC, ymhari commented on db/migrate/20210803162052_migrate_thm_csr_variant.rb
> +  def self.up
Why are we not using a rake instead?

2021-08-20 14:12 UTC, jayreddy519 commented
PR No longer Needed.

2021-08-20 14:12 UTC, closed without merging