Disable Contact Center Email
ideacrew/enroll pull request #679
Opened 2021-08-08 19:09 UTC by jacobkagon

### Master Pivotal ticket
* https://www.pivotaltracker.com/n/projects/2481179/stories/179155265

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2021-08-09 13:22 UTC, ZASMan requested changes

2021-08-09 13:22 UTC, ZASMan commented on features/step_definitions/footer_steps.rb
> +  expect(page).to have_content("info@dchealthlink.com")
Change this to
```
expect(page).to have_content(EnrollRegistry[:enroll_app].setting(:mail_address).item)
```

2021-08-09 13:22 UTC, ZASMan commented on features/step_definitions/footer_steps.rb
> +Given(/email address feature is enabled?/) do
Get rid of these steps, use:
```
And EnrollRegistry contact_email_feature feature is enabled
```

See `resource_registry_world`

2021-08-09 13:22 UTC, ZASMan commented on app/views/ui-components/bs4/v1/footers/_footer.slim
> +                    = Settings.contact_center.email_address
Change this to `EnrollRegistry[:enroll_app].setting(:mail_address).item`

2021-08-09 13:22 UTC, ZASMan commented on app/views/ui-components/v1/layouts/_footer.html.slim
> +                  = Settings.contact_center.email_address
Change this to `EnrollRegistry[:enroll_app].setting(:mail_address).item`

2021-08-09 13:22 UTC, ZASMan commented on config/client_config/me/system/config/templates/features/enroll_app/enroll_app.yml
> +      - key: contact_email_feature
Come up with a name like header_footer

2021-08-10 15:19 UTC, bill-transue approved these changes
Good job incorporating Zane's feedback. Let me know when you get this rebased and we can merge. Thanks @jacobkagon!

2021-08-10 16:20 UTC, merged